// Generated by CoffeeScript 1.7.1
var Hero, bar, batman, cubes, foo, limit, num, one, player, result, six, source, three, two, x, zip, _i, _j, _k, _ref, _ref1, _ref2, _ref3, _ref4, _results;

foo = 42;

player = {
  name: 'Pegasus',
  age: 'MMXIV'
};

limit = typeof max_limit !== "undefined" && max_limit !== null ? max_limit : 5;

bar = Math.pow(8, 2);

cubes = (function() {
  var _i, _len, _ref, _results;
  _ref = [25, 64, 100];
  _results = [];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    num = _ref[_i];
    _results.push(Math.sqrt(num));
  }
  return _results;
})();

foo = (function() {
  var _i, _results;
  _results = [];
  for (x = _i = 0; _i <= 100; x = ++_i) {
    _results.push(x);
  }
  return _results;
})();

bar = (function() {
  var _i, _results;
  _results = [];
  for (x = _i = 0; _i <= 100; x = ++_i) {
    if (x < 10 || x > 20) {
      _results.push(x);
    }
  }
  return _results;
})();

for (x = _i = 0; _i <= 100; x = ++_i) {
  console.log(x);
}

foo = (function() {
  var _j, _results;
  _results = [];
  for (x = _j = 1; _j <= 10; x = ++_j) {
    _results.push(Math.pow(2, x));
  }
  return _results;
})();

foo = ((_ref = $('.buttons').getPosition()) != null ? _ref.left : void 0) || 0;

if ((typeof ignition !== "undefined" && ignition !== null) === true) {
  launch();
}

zip = typeof data !== "undefined" && data !== null ? (_ref1 = data.users) != null ? (_ref2 = _ref1.paul) != null ? _ref2.money : void 0 : void 0 : void 0;

six = (one = 1) + (two = 2) + (three = 3);

foo = (function() {
  if ((_ref3 = typeof jQuery !== "undefined" && jQuery !== null ? jQuery : underscore) != null) {
    return _ref3;
  } else {
    throw Error('Missing jQuery and underscore');
  }
})();

$(function() {
  return $('#logo');
}).addClass('foo').click(function() {
  return $(this).hide();
});

foo = {
  name: 'Slim Shady',
  hello: function() {
    return "Hi, I'm " + this.name;
  }
};

foo.hello();

foo = "today is " + (new Date().toLocaleDateString());

foo = (function() {
  _results = [];
  for (var _j = 0, _ref4 = Math.random() * 10 + 5; 0 <= _ref4 ? _j <= _ref4 : _j >= _ref4; 0 <= _ref4 ? _j++ : _j--){ _results.push(_j); }
  return _results;
}).apply(this);

source = [0, 5, 9];

for (_k = 0; _k < 2; _k++) {
  result = (result != null ? result : []).concat(source);
}

$('form').submit(function() {
  return $(this).find('.ajax-loader').show();
});

Hero = (function() {
  function Hero(name) {
    this.name = name;
  }

  Hero.prototype.fight = function(enemy) {
    return "" + this.name + " just attacked " + enemy + "!";
  };

  return Hero;

})();

batman = new Hero('Batman');

batman.fight('the Joker');
